name: Application host started
contributors:
- Jose Rodriguez @Cyb3rPandaH
- Roberto Rodriguez @Cyb3rWard0g
attack:
  data_source: Powershell log
  data_component: powershell context
relationship:
  source: application host
  link: started
  target: null
security_events:
- name: Engine state is changed from None to Available.
  event_id: 400
  platform: Windows
  audit_category: Engine Lifecycle
  log_channel: Windows PowerShell
  log_provider: PowerShell
