name: Application domain started
contributors:
- Jose Rodriguez @Cyb3rPandaH
- Roberto Rodriguez @Cyb3rWard0g
attack:
  data_source: Powershell log
  data_component: powershell context
relationship:
  source: application domain
  link: started
  target: null
security_events:
- name: Windows PowerShell has started an IPC listening thread on a process in AppDomain.
  event_id: 53504
  platform: Windows
  audit_category: PowerShell Named Pipe IPC
  log_channel: Microsoft-Windows-PowerShell/Operational
  log_provider: Microsoft-Windows-PowerShell
